### ISSUE TITLE
Tap To Connect functionality

### ISSUE THREAD

**Issue by svsobh** [semlette/nfc_in_flutter#16]

**Comment by semlette** [comment]
Hi, thank you for the kind words.

"Tap to connect" functionality is possible to do with NFC, but it may be difficult.

Phones do not have a built-in NFC tag, so you can't "just read" another phone. However if you emulate a tag on the phone's NFC chip, you *can* read from that phone. This is called host card emulation.
Both iOS and Android can read emulated tags, however **only Android can emulate tags**.

nfc_in_flutter does not have functions to emulate tags, so you would have to research how to emulate tags on Android, and then communicate with Flutter using a Platform channel.
