### ISSUE TITLE
It's better to change minsdkversion to 17?

### ISSUE THREAD

**Issue by ryanhz** [semlette/nfc_in_flutter#43]
In a flutter project created earlier, I got this error on build apk:

android/app/src/main/AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 17 cannot be smaller than version 19 declared in library [:nfc_in_flutter] 
build/nfc_in_flutter/intermediates/library_manifest/release/AndroidManifest.xml as the library might be using APIs not available in 17
        Suggestion: use a compatible library with a minSdk of at most 17,                                          
                or increase this project's minSdk version to at least 19,                                          
                or use tools:overrideLibrary="me.andisemler.nfc_in_flutter" to force usage (may lead to runtime failures)
                                                                                                                   
FAILURE: Build failed with an exception.                                                                           
                                                                                                                   
* What went wrong:                                                                                                 
Execution failed for task ':app:processReleaseManifest'.                                                           
> Manifest merger failed : uses-sdk:minSdkVersion 17 cannot be smaller than version 19 declared in library [:nfc_in_flutter] build/nfc_in_flutter/intermediates/library_manifest/release/AndroidManifest.xml as the library might be using APIs not available in 17
        Suggestion: use a compatible library with a minSdk of at most 17,                                          
                or increase this project's minSdk version to at least 19,                                          
                or use tools:overrideLibrary="me.andisemler.nfc_in_flutter" to force usage (may lead to runtime failures)
                                                                                                                   
* Try:                                                                                                             
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                                                                   
* Get more help at https://help.gradle.org

**Comment by semlette** [comment]
minSdkVersion=19 is intentional. I would like to add support for emulating host card emulation in the future and that requires SDK v19.

Then again, SDK v19 released back in 2013.

The README was supposed to mention the minSdkVersion=19 requirement, but I guess I forgot.

**Comment by ryanhz** [comment]
Thanks for clarify,  we are so looking forwards to HCE.
