### ISSUE TITLE
New Tag Collected NFC android

### ISSUE THREAD

**Issue by mavbcn** [semlette/nfc_in_flutter#46]
Hello,
I'm trying to read a tag , wait 2 seconds, and then write a new value to confirm an operation. The problem is that in android appears the New Tag Collected notification How can avoid this? 
what should I set up in the app? 
I have this in my androidmanifest

            <intent-filter>
                <action android:name="android.nfc.action.NDEF_DISCOVERED"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <data android:mimeType="text/plain" />
            </intent-filter>    

please let me know
thanks

**Comment by James-A-White** [comment]
I see you have closed this. Can you share your solution with us?

**Comment by ghulamsabir5353** [comment]
Hey can you please share solution how to stop this "New Tag Collected" in Android
