### ISSUE TITLE
Can't read UUID

### ISSUE THREAD

**Issue by ryanhz** [semlette/nfc_in_flutter#49]
Below is my code:

	void scan() async {
		// Start reading using NFC.readNDEF()
		_stream = NFC.readNDEF(
			once: false,
			throwOnUserCancel: false,
		).listen((NDEFMessage message) async {
			print("read NDEF message: ${message.payload}");
			uuid = message.id;
			content = message.data;
			content = content ??  "";
			setState(() {});
		}, onError: (e) {
			// Check error handling guide below
			handleError(e);
		});

running on ios, I can't get the UUID of tag

**Comment by the-white-cat** [comment]
It seems there's no way to read the UUID because the framework uses NFCNDEFReaderSession instead of NFCTagReaderSession. And iOS doesn't read the UUIDs in ndef session
Stuck with the same problem :(

**Comment by semlette** [comment]
Daring souls can clone the tags branch, which has support for reading tags on iOS.

Absolutely no guarantee on its stability.
