### ISSUE TITLE
Adding reading of NFC TAG ID

### ISSUE THREAD

**Issue by SWAG-DevTeam** [semlette/nfc_in_flutter#7]
Il would be good to add support to NFC tag ID (tag unique serial number) on tag reading.

Please do you plan to add such feature ?

**Comment by semlette** [comment]
Hi

I am currently working on a big update that will indeed make it possible to get the tag’s UID.
Note that it will not be possible on Apple devices running iOS < 13 due to API restrictions.

**Comment by SWAG-DevTeam** [comment]
This is a good news.

I Heard about spacial API that make it possible on iOS.
https://forums.developer.apple.com/thread/89287

What do you think about it ?

**Comment by semlette** [comment]
Reading about Private APIs on iOS, it seems clear that Apple will reject your app on the App Store if you use private APIs. I don’t want anyone’s apps to be rejected just because this plugin used 1 private API.

**Comment by SWAG-DevTeam** [comment]
This IS a great news.
Thank you very much. Congratulations for this achivement.

**Comment by SergeShkurko** [comment]
Any news about support UID reading on ios?

**Comment by SergeShkurko** [comment]
[NFC Tools app for ios](https://apps.apple.com/ru/app/nfc-tools/id1252962749) already support it
![IMG_0196](https://user-images.githubusercontent.com/18213789/78452846-8367a080-7696-11ea-8a9e-f4554edf429a.jpg)
