### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by larssn** [semlette/nfc_in_flutter#83]
The official guide can be found here: https://dart.dev/null-safety/migration-guide

If no one volunteers, I might be able to do it in a few weeks.

**Comment by ZippyRainbow** [comment]
Sounds Good larssn, looking forward to it, one of my last modules needing Null Safety.

**Comment by larssn** [comment]
> Sounds Good larssn, looking forward to it, one of my last modules needing Null Safety.

I did a PR a few days back. Check it out if you have the time.

**Comment by ZippyRainbow** [comment]
> > Sounds Good larssn, looking forward to it, one of my last modules needing Null Safety.
> 
> I did a PR a few days back. Check it out if you have the time.

Thanks, great. I will when I get a chance.

**Comment by ZippyRainbow** [comment]
Hey @larssn , I am not really too up to speed with how I can test your changes, but from the looks of the notes under "About" it says that this project is "Not maintained anymore.".. Maybe we need to contact @semlette to see if we can get access to merge some of these changes.

**Comment by jomag** [comment]
Any chance that this will be fixed? @semlette 

The package was working great, but now it will not build anymore...
