### ISSUE TITLE
Error: NDEF Tag does not contain any NDEF Message on iOS

### ISSUE THREAD

**Issue by Nico1911** [semlette/nfc_in_flutter#87]
Hello, 
I tried to build an NFC App and it works still fine - beside one big problem. When I want to describe a newly purchased NFC tag, already formatted for NDEF, with my app, this does not work with the error code: ERROR: NDEF tag does not contain any NDEF message. However, if I open another NFC app from the AppStore, it works perfectly with the tag. It is also strange that once I have written a text to the tag with another NFC App, my app now works perfectly and I can now write to the tag.

So my question is, why can I only write NFC tags with my app that already contain a message?

I would also be interested to know how I could programme my app so that it can also write to empty tags. Since this also works with the other app from the AppStore, it must be possible with iOS.

Many thanks in advance to all those who take the time to deal with my question.

[https://stackoverflow.com/questions/67147077/flutter-error-ndef-tag-does-not-contain-any-ndef-message-on-ios/67153374#67153374](url)

**Comment by vilvic** [comment]
I believe I have fixed this on my branch

https://github.com/vilvic/nfc_in_flutter

**Comment by Nico1911** [comment]
Thank you for your answer!
However, after thinking about it for a while and trying it out, I haven't found a way to implement this solution in my Dart function so that it works for me. Also, because I am absolutely not familiar with the programming language in which you wrote the solution. Would you perhaps have an approach for me, how I could incorporate your solution there?

`Future<void> writeToTag() async{
  try {

    final result = await InternetAddress.lookup('google.com');

    if (result.isNotEmpty && result[0].rawAddress.isNotEmpty) {
      

      if (Platform.isAndroid) {
        showDialog(
          context: context,
          builder: (context) => AlertDialog(
            title: const Text("Halten Sie Ihr Gerät an den Chip, den Sie lesen möchten"),
            actions: <Widget>[
              FlatButton(
                child: const Text("Cancel"),
                onPressed: () {
                  _stream?.cancel();
                  Navigator.pop(context);
                },
              ),
            ],
          ),
        );
      }



      List <NDEFRecord> my = [NDEFRecord.type("Chip", _random)];
      NDEFMessage Message = NDEFMessage.withRecords(my);

      await NFC.writeNDEF(Message, once: true).first;
      funktinoiert.year = true;

      setState(() {
        isloading = true;
      });

      int time = DateTime.now().millisecondsSinceEpoch;


      Map<String, dynamic> data = {
        "random" : _random,
        "Time" : time,
      };

      await Firestore.instance
          .collection("NFC")
          .document(_random)
          .setData(data)
          .catchError((e) {
        funktinoiert.year = false;
        print(e);
      });

      await Firestore.instance
          .collection("Anzahl")
          .document("Prototyp")
          .updateData({"NFC": FieldValue.increment(1)})
          .catchError((e) {
        print(e);
      });
    }

  }
  on FirebaseException catch (e) {
    newEntryFehlermeldung("$e \n\n Bitte versuchen Sie es erneut. Sollten Sie den Fehler nicht beheben können hilft unser Team Ihnen gerne weiter.");
    funktinoiert.year = false;
  } on PlatformException {
    newEntryFehlermeldung("Es ist ein Fehler aufgetreten, bitte versuchen Sie es erneut");
    funktinoiert.year = false;
  } on NFCUserCanceledSessionException {
    funktinoiert.year = false;
    return null;
  } on NFCSessionTerminatedUnexpectedlyException {
    newEntryFehlermeldung("Es ist ein Fehler aufgetreten, bitte versuchen Sie es erneut");
    funktinoiert.year = false;
  } on NFCSessionTimeoutException {
    newEntryFehlermeldung("Es ist ein Fehler aufgetreten, bitte versuchen Sie es erneut");
    funktinoiert.year = false;
  } on NFCTagNotWritableException {
    newEntryFehlermeldung("Es sieht so aus, als wäre der Chip nicht beschreibbar. Bitte versuchen Sie es erneut.");
    funktinoiert.year = false;
  } on NFCTagSizeTooSmallException {
    newEntryFehlermeldung("Es ist ein Fehler aufgetreten, bitte versuchen Sie es erneut");
    funktinoiert.year = false;
  } on NFCTagUnwritableException {
    newEntryFehlermeldung("Es ist ein Fehler aufgetreten, bitte versuchen Sie es erneut");
    funktinoiert.year = false;
  } on NFCTagUnavailableException {
    newEntryFehlermeldung("Es ist ein Fehler aufgetreten, bitte versuchen Sie es erneut");
    funktinoiert.year = false;
  } on NFCSystemIsBusyException {
    newEntryFehlermeldung("Es ist ein Fehler aufgetreten, bitte versuchen Sie es erneut");
    funktinoiert.year = false;
  } on Exception catch (exception) {
    newEntryFehlermeldung("$exception \n\n Bitte versuchen Sie es erneut. Sollten Sie den Fehler nicht beheben können hilft unser Team Ihnen gerne weiter.");
    funktinoiert.year = false;
    Navigator.pushReplacementNamed(context, "/home");
    print(exception);
  } catch (e) {
    funktinoiert.year = false;
    newEntryFehlermeldung("Es besteht keine Verbindung zum Internet. Bitte versuchen Sie es erneut. Sollten Sie den Fehler nicht beheben können hilft unser Team Ihnen gerne weiter.");
  }


  if(funktinoiert.year == true){
    newEntry();
    funktinoiert.year = false;
  } else{
    newEntryFehlermeldung("Es ist ein Fehler aufgetreten, bitte versuchen Sie es erneut");
  }


  setState(() {
    isloading = false;
  });

  Navigator.pushReplacementNamed(context, "/home");
}`

**Comment by Nico1911** [comment]
Thank you!
